apiVersion: v1
kind: Service
metadata:
  name: k8s-2
  namespace: microservices
spec:
  type: NodePort
  selector:
    app: k8s-2
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30081  # Puerto externo en Minikube
