apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: microservices
resources:
- ../base
configMapGenerator:
- envs:
  - variables.properties
  name: k8s-4-memory
  options:
    disableNameSuffixHash: true
patches:
  # Patch Deployment
  - target:
      kind: Deployment
      name: ms
    patch: |-
      - op: replace
        path: /metadata/name
        value: k8s-4-memory
      - op: replace
        path: /spec/selector/matchLabels/app
        value: k8s-4-memory
      - op: replace
        path: /spec/template/metadata/labels/app
        value: k8s-4-memory
      - op: replace
        path: /spec/template/spec/containers/0/name
        value: k8s-4-memory
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: k8s-4-memory:latest
  
  # Patch Service
  - target:
      kind: Service
      name: ms
    patch: |-
      - op: replace
        path: /metadata/name
        value: k8s-4-memory
      - op: replace
        path: /spec/selector/app
        value: k8s-4-memory

  # Patch HPA
  - target:
      kind: HorizontalPodAutoscaler
      name: ms
    patch: |-
      - op: replace
        path: /metadata/name
        value: k8s-4-memory
      - op: replace
        path: /spec/scaleTargetRef/name
        value: k8s-4-memory
      - op: replace
        path: /spec/minReplicas
        value: 1
      - op: replace
        path: /spec/maxReplicas
        value: 3
    